include:
  - local: 'variables.yml'

stages:
  - push
  
.push:
  stage: push
  image: ${CI_CD_DOCKER_IMAGE_NAME}:${CI_CD_DOCKER_IMAGE_VERSION}
  script:
    - echo "Repo url - ${HELM_REPO_URL}"
    - helm repo add --username ${HELM_REPO_USER} --password ${HELM_REPO_PASS} ${HELM_REPO_NAME} ${HELM_REPO_URL}
    - helm cm-push ./${FOLDER} ${HELM_REPO_NAME}
  rules:
    - changes: 
      - ${FOLDER}/Chart.yaml
