include:
  - local: 'variables.yml'

stages:
  - Push
  
.push:
  stage: Push
  image: 
    name: alpine/helm:3.14.4
    entrypoint: [""]
  variables:
    HELM_EXPERIMENTAL_OCI: "1"
  script:
    - export CHART_VERSION=$(grep 'version:' ${FOLDER}/Chart.yaml | cut -d ' ' -f 2)
    - helm registry login ${HELM_REPO_URL} -u ${HELM_REPO_USER} -p ${HELM_REPO_PASS}
    - helm dependency update ${FOLDER} 
    - helm package ${FOLDER} --version ${CHART_VERSION}
    - helm push ${FOLDER}-${CHART_VERSION}.tgz oci://${HELM_REPO_URL}
  after_script:
    - echo "HELM_REPO_URL=${HELM_REPO_URL}"
  rules:
    - changes: 
      - ${FOLDER}/Chart.yaml
  tags: 
  - $RUNNER_TAG
