include:
  - local: 'variables.yml'

stages:
  - Push
  
.push:
  stage: Push
  image: 
    name: alpine/helm:3.14.4
    entrypoint: [""]
  script:
    - helm repo add --username ${HELM_REPO_USER} --password ${HELM_REPO_PASS} ${HELM_REPO_NAME} ${HELM_REPO_URL}
    - export CHART_VERSION=$(grep 'version:' ${FOLDER}/Chart.yaml | cut -d ' ' -f 2)
    - helm package ${FOLDER} --version $CHART_VERSION
    - helm push ${FOLDER}-$CHART_VERSION.tgz ${HELM_REPO_NAME}
  after_script:
    - echo "HELM_REPO_URL=${HELM_REPO_URL}"
  rules:
    - changes: 
      - ${FOLDER}/Chart.yaml
  tags: 
  - $RUNNER_TAG
