include:
  - local: variables.yml

stages:
  - plan
  - apply

variables:
  TF_HTTP_PASSWORD: ${CI_JOB_TOKEN}

.terraform:
  image: ${CI_CD_DOCKER_IMAGE_NAME}:${CI_CD_DOCKER_IMAGE_VERSION}
  script:
    - cd ${FOLDER}
    - terraform init
    - terraform $TERRAFORM_ACTION
