include:
  - local: variables.yml

stages:
  - Plan
  - Apply

variables:
  TF_HTTP_PASSWORD: "${CI_JOB_TOKEN}"
  TF_IN_AUTOMATION: "true"
  TF_VAR_HELM_REPO_PASS: "${CI_JOB_TOKEN}"

.terraform:
  image: ${CI_CD_DOCKER_IMAGE_NAME}:${CI_CD_DOCKER_IMAGE_VERSION}
  script:
    - ${ACTION}
  tags: 
  - ${BUILD_RUNNER_TAG}

.plan:
  extends: .terraform
  stage: Plan
  variables:
    ACTION: "task plan"
  artifacts:
    paths:
    - ${DIR}/.terraform/plan.out
    expire_in: 30 min
  rules:
  - changes:
    - ${DIR}/*
    when: always

.apply:
  extends: .terraform
  stage: Apply
  variables:
    ACTION: "task apply:force"
  rules:
  - if: '$CI_COMMIT_REF_NAME == "master" || $CI_COMMIT_REF_NAME == "main"'
    changes:
    - ${DIR}/*
    when: manual

.plan_all:
  extends: .plan
  variables:
    ACTION: "task plan:all"

.apply_all:
  extends: .apply
  variables:
    ACTION: "task apply:all:force"
