include:
  - local: functions/build_kaniko.yml

Build:
  stage: build
  extends: .build
  variables:
    BUILD_ADDITION: "--platform linux/arm/v7"
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    